export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const REMOVE_USER_INFO = 'REMOVE_USER_INFO'
export const SET_COLLAPSE = 'SET_COLLAPSE'
export const SET_ROUTES = 'SET_ROUTES'
export const SET_ROLES = 'SET_ROLES'